# Generated by Django 4.2.1 on 2023-06-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
