# Generated by Django 4.2.1 on 2023-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
