# Generated by Django 4.2.1 on 2023-07-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_onlineitem_category'),
        ('marketplace', '0007_carta_cart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_id',
        ),
        migrations.AddField(
            model_name='carta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.onlineitem'),
            preserve_default=False,
        ),
    ]
