# Generated by Django 4.2.1 on 2023-07-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_cart_item_id_carta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
    ]
