# Generated by Django 4.2.1 on 2023-05-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='onlineitem',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
